'use strict'

const ERROR_MAP = {
  110: 'hashrate_low',
  111: 'power_init_error',
  120: 'fan_speed_error',
  121: 'fan_speed_error',
  130: 'fan_speed_error',
  131: 'fan_speed_error',
  140: 'fan_speed_too_high',
  200: 'power_probing_error',
  201: 'power_config_mismatch',
  202: 'power_output_voltage_error',
  203: 'power_protecting',
  204: 'power_current_protecting',
  205: 'power_current_error',
  206: 'power_input_voltage_low',
  207: 'power_input_current_protecting',
  210: 'power_error_status',
  213: 'power_input_voltage_current_mismatch',
  216: 'power_remained_unchanged',
  217: 'power_set_enable_error',
  218: 'power_input_voltage_low_for_high_power',
  219: 'power_input_current_incorrect',
  233: 'power_output_over_temp_protection',
  234: 'power_output_over_temp_protection',
  235: 'power_output_over_temp_protection',
  236: 'power_output_overcurrent_protection',
  237: 'power_output_overcurrent_protection',
  238: 'power_output_overcurrent_protection',
  239: 'power_output_overvoltage_protection',
  240: 'power_output_overvoltage_protection',
  241: 'power_input_low_voltage_protection',
  243: 'power_input_overvoltage_protection',
  244: 'power_input_overvoltage_protection',
  245: 'power_input_overvoltage_protection',
  246: 'power_input_overcurrent_protection',
  247: 'power_input_overcurrent_protection',
  248: 'power_input_overvoltage_protection',
  249: 'power_input_overvoltage_protection',
  250: 'power_input_low_voltage_protection',
  251: 'power_input_low_voltage_protection',
  253: 'power_fan_error',
  254: 'power_fan_error',
  255: 'power_output_over_temp_protection',
  256: 'power_output_over_temp_protection',
  257: 'power_input_overcurrent_protection',
  263: 'power_probing_error',
  264: 'power_probing_error',
  267: 'power_probing_error',
  268: 'power_output_overcurrent_protection',
  269: 'power_input_overcurrent_protection',
  270: 'power_input_overvoltage_protection',
  271: 'power_input_low_voltage_protection',
  272: 'power_input_overcurrent_protection',
  273: 'power_input_overcurrent_protection',
  274: 'power_fan_error',
  275: 'power_over_temp_warning',
  300: 'temp_sensor_detection_error',
  301: 'temp_sensor_detection_error',
  302: 'temp_sensor_detection_error',
  303: 'temp_sensor_detection_error',
  320: 'temp_reading_error',
  321: 'temp_reading_error',
  322: 'temp_reading_error',
  323: 'temp_reading_error',
  329: 'temp_sensor_detection_error',
  350: 'temp_protecting',
  351: 'temp_protecting',
  352: 'temp_protecting',
  353: 'temp_protecting',
  360: 'hashboard_temp_overheating',
  370: 'env_temp_fluctuates_too_much',
  410: 'eeprom_detect_error',
  411: 'eeprom_detect_error',
  412: 'eeprom_detect_error',
  413: 'eeprom_detect_error',
  420: 'eeprom_parser_error',
  421: 'eeprom_parser_error',
  422: 'eeprom_parser_error',
  423: 'eeprom_parser_error',
  430: 'eeprom_xfer_error',
  431: 'eeprom_xfer_error',
  432: 'eeprom_xfer_error',
  433: 'eeprom_xfer_error',
  440: 'eeprom_xfer_error',
  441: 'eeprom_xfer_error',
  442: 'eeprom_xfer_error',
  443: 'eeprom_xfer_error',
  450: 'eeprom_xfer_error',
  451: 'eeprom_xfer_error',
  452: 'eeprom_xfer_error',
  453: 'eeprom_xfer_error',
  500: 'no_software_config_added',
  510: 'control_board_no_support_chip',
  511: 'control_board_no_support_chip',
  512: 'control_board_no_support_chip',
  513: 'control_board_no_support_chip',
  530: 'hashboard_error',
  520: 'hashboard_error',
  521: 'hashboard_error',
  522: 'hashboard_error',
  523: 'hashboard_error',
  531: 'hashboard_error',
  532: 'hashboard_error',
  533: 'hashboard_error',
  540: 'hashboard_error',
  541: 'hashboard_error',
  542: 'hashboard_error',
  543: 'hashboard_error',
  550: 'hashboard_error',
  551: 'hashboard_error',
  552: 'hashboard_error',
  553: 'hashboard_error',
  560: 'hashboard_error',
  561: 'hashboard_error',
  562: 'hashboard_error',
  563: 'hashboard_error',
  600: 'env_temp_high',
  610: 'high_temp_return_to_normal',
  701: 'control_board_no_support_chip',
  710: 'control_board_exception',
  712: 'control_board_exception',
  800: 'cgminer_checksum_error',
  801: 'system_monitor_checksum_error',
  802: 'remote_daemon_checksum_error',
  810: 'air_to_liquid_pcbsn_not_match',
  2000: 'no_pool_info_configured',
  2010: 'all_pools_disabled',
  2020: 'pool_connect_failed',
  2021: 'pool_connect_failed',
  2022: 'pool_connect_failed',
  2030: 'high_rejection_rate_pool',
  2040: 'pool_not_support_asicboost',
  2050: 'switch_to_new_pool_failed',
  2310: 'hashrate_low',
  2320: 'hashrate_low',
  2340: 'high_loss_of_hash_rate',
  2350: 'high_loss_of_hash_rate',
  5110: 'frequency_up_timeout',
  5111: 'frequency_up_timeout',
  5112: 'frequency_up_timeout',
  5113: 'frequency_up_timeout',
  5070: 'water_velocity_abnormal',
  5071: 'water_velocity_abnormal',
  5072: 'water_velocity_abnormal',
  5073: 'water_velocity_abnormal',
  8000: 'version_low',
  8410: 'software_version_error',
  100001: 'antiv_signature_illegal',
  100002: 'antiv_dig_initd_dig_illegal',
  100003: 'antiv_dig_pf_partial_dig_illegal'
}

// M63S++ (miner-wm-m63spp) uses the full granular WhatsMiner error table.
// Kept separate from ERROR_MAP so other miner types are not affected.
const M63SPP_ERROR_MAP = {
  200: 'power_probing_error',
  201: 'power_config_mismatch',
  202: 'power_output_voltage_error',
  203: 'power_protecting',
  204: 'power_current_protecting',
  205: 'power_current_error',
  206: 'power_input_voltage_low',
  207: 'power_input_current_protecting',
  208: 'power_power_error',
  209: 'power_voltage_offset_error',
  210: 'power_error_status',
  211: 'power_output_current_deviation',
  212: 'power_output_voltage_margin_low',
  213: 'power_input_voltage_current_mismatch',
  214: 'power_pin_did_not_change',
  215: 'power_vout_set_error',
  216: 'power_remained_unchanged',
  217: 'power_set_enable_error',
  218: 'power_input_voltage_low_for_high_power',
  233: 'power_output_over_temp_protection',
  236: 'power_output_overcurrent_protection',
  246: 'power_input_overcurrent_protection',
  250: 'power_input_low_voltage_protection',
  251: 'power_input_undervoltage_protection',
  253: 'psu_fan_detection_error',
  254: 'psu_fan_detection_error',
  257: 'power_primary_overcurrent_protection',
  263: 'power_communication_warning',
  264: 'power_communication_error',
  270: 'power_input_overvoltage_protection',
  274: 'psu_fan_warning',
  275: 'power_over_temp_warning',
  300: 'temp_sensor_detection_error',
  301: 'temp_sensor_detection_error',
  302: 'temp_sensor_detection_error',
  303: 'temp_sensor_detection_error',
  320: 'temp_reading_error',
  321: 'temp_reading_error',
  322: 'temp_reading_error',
  323: 'temp_reading_error',
  326: 'liquid_temp_sensor_comm_error',
  329: 'control_board_temp_sensor_error',
  350: 'temp_protecting',
  351: 'temp_protecting',
  352: 'temp_protecting',
  353: 'temp_protecting',
  360: 'hashboard_temp_overheating',
  370: 'env_temp_fluctuates_too_much',
  380: 'humidity_sensor_not_found',
  381: 'humidity_sensor_reading_error',
  382: 'humidity_sensor_reading_error',
  383: 'humidity_sensor_protecting',
  400: 'eeprom_unknown_error',
  410: 'eeprom_detect_error',
  411: 'eeprom_detect_error',
  412: 'eeprom_detect_error',
  413: 'eeprom_detect_error',
  420: 'eeprom_parser_error',
  421: 'eeprom_parser_error',
  422: 'eeprom_parser_error',
  423: 'eeprom_parser_error',
  430: 'eeprom_chip_bin_type_error',
  431: 'eeprom_chip_bin_type_error',
  432: 'eeprom_chip_bin_type_error',
  433: 'eeprom_chip_bin_type_error',
  440: 'eeprom_chip_num_error',
  441: 'eeprom_chip_num_error',
  442: 'eeprom_chip_num_error',
  443: 'eeprom_chip_num_error',
  450: 'eeprom_xfer_error',
  451: 'eeprom_xfer_error',
  452: 'eeprom_xfer_error',
  453: 'eeprom_xfer_error',
  500: 'hashboard_error',
  510: 'hashboard_miner_type_error',
  511: 'hashboard_miner_type_error',
  512: 'hashboard_miner_type_error',
  513: 'hashboard_miner_type_error',
  520: 'hashboard_bin_type_mismatch',
  521: 'hashboard_bin_type_mismatch',
  522: 'hashboard_bin_type_mismatch',
  523: 'hashboard_bin_type_mismatch',
  530: 'hashboard_not_found',
  531: 'hashboard_not_found',
  532: 'hashboard_not_found',
  533: 'hashboard_not_found',
  540: 'hashboard_reading_chip_id_error',
  541: 'hashboard_reading_chip_id_error',
  542: 'hashboard_reading_chip_id_error',
  543: 'hashboard_reading_chip_id_error',
  550: 'hashboard_bad_chips',
  551: 'hashboard_bad_chips',
  552: 'hashboard_bad_chips',
  553: 'hashboard_bad_chips',
  560: 'hashboard_loss_balance',
  561: 'hashboard_loss_balance',
  562: 'hashboard_loss_balance',
  563: 'hashboard_loss_balance',
  570: 'hashboard_chip_xfer_error',
  571: 'hashboard_chip_xfer_error',
  572: 'hashboard_chip_xfer_error',
  573: 'hashboard_chip_xfer_error',
  580: 'hashboard_reset_error',
  581: 'hashboard_reset_error',
  582: 'hashboard_reset_error',
  583: 'hashboard_reset_error',
  590: 'hashboard_frequency_too_low',
  591: 'hashboard_frequency_too_low',
  592: 'hashboard_frequency_too_low',
  593: 'hashboard_frequency_too_low',
  600: 'env_temp_high',
  610: 'high_temp_return_to_normal',
  620: 'liquid_cooling_temp_protection',
  652: 'liquid_temp_fluctuation_high',
  700: 'mac_address_invalid',
  701: 'control_board_no_support_chip',
  702: 'control_board_version_unknown',
  710: 'control_board_exception',
  711: 'control_board_exception',
  712: 'control_board_exception',
  714: 'network_connection_unstable',
  800: 'cgminer_checksum_error',
  801: 'system_monitor_checksum_error',
  802: 'remote_daemon_checksum_error',
  810: 'air_to_liquid_pcbsn_not_match',
  820: 'air_to_liquid_psusn_not_match',
  901: 'power_rate_error',
  2000: 'no_pool_info_configured',
  2010: 'all_pools_disabled',
  2020: 'pool_connect_failed',
  2021: 'pool_connect_failed',
  2022: 'pool_connect_failed',
  2030: 'high_rejection_rate_pool',
  2040: 'pool_not_support_asicboost',
  2050: 'switch_to_new_pool_failed',
  2110: 'hashboard_factory_test_failed',
  2111: 'hashboard_factory_test_failed',
  2112: 'hashboard_factory_test_failed',
  2113: 'hashboard_factory_test_failed',
  2310: 'hashrate_too_low',
  2320: 'hashrate_too_low',
  2340: 'high_loss_of_hash_rate',
  2350: 'high_loss_of_hash_rate',
  5010: 'chip_voltage_too_low',
  5011: 'chip_voltage_too_low',
  5012: 'chip_voltage_too_low',
  5013: 'chip_voltage_too_low',
  5020: 'chip_voltage_change',
  5021: 'chip_voltage_change',
  5022: 'chip_voltage_change',
  5023: 'chip_voltage_change',
  5030: 'chip_temp_difference_large',
  5031: 'chip_temp_difference_large',
  5032: 'chip_temp_difference_large',
  5033: 'chip_temp_difference_large',
  5040: 'chip_hottest_temp_difference_large',
  5041: 'chip_hottest_temp_difference_large',
  5042: 'chip_hottest_temp_difference_large',
  5043: 'chip_hottest_temp_difference_large',
  5070: 'water_velocity_abnormal',
  5071: 'water_velocity_abnormal',
  5072: 'water_velocity_abnormal',
  5073: 'water_velocity_abnormal',
  5079: 'liquid_flow_rate_too_slow',
  5110: 'frequency_up_timeout',
  5111: 'frequency_up_timeout',
  5112: 'frequency_up_timeout',
  5113: 'frequency_up_timeout',
  8000: 'version_low',
  8010: 'frequency_not_up_to_standard',
  8020: 'hashrate_not_up_to_standard',
  8400: 'wrong_software_version',
  8410: 'software_version_error',
  100000: 'security_library_error',
  100100: 'security_btminer_removed',
  110000: 'security_illegal_file',
  110001: 'security_virus_removed',
  520001: 'chip_error_nonce',
  520002: 'chip_error_nonce',
  520003: 'chip_error_nonce',
  521001: 'chip_error_nonce',
  521002: 'chip_error_nonce',
  521003: 'chip_error_nonce',
  522001: 'chip_error_nonce',
  522002: 'chip_error_nonce',
  522003: 'chip_error_nonce',
  523000: 'chip_error_nonce',
  523001: 'chip_error_nonce',
  523002: 'chip_error_nonce',
  523003: 'chip_error_nonce',
  530001: 'chip_few_nonce',
  530002: 'chip_few_nonce',
  530003: 'chip_few_nonce',
  531001: 'chip_few_nonce',
  531002: 'chip_few_nonce',
  531003: 'chip_few_nonce',
  532001: 'chip_few_nonce',
  532002: 'chip_few_nonce',
  532003: 'chip_few_nonce',
  533001: 'chip_few_nonce',
  533002: 'chip_few_nonce',
  533003: 'chip_few_nonce',
  540000: 'chip_temp_protected',
  540001: 'chip_temp_protected',
  540002: 'chip_temp_protected',
  540003: 'chip_temp_protected'
}

const API_MAP = {
  14: 'Invalid API command or data',
  23: 'Invalid JSON message',
  45: 'Permission denied',
  131: 'OK',
  132: 'Command error',
  134: 'Get token OK',
  135: 'Token error',
  136: 'Too many tokens',
  137: 'Base64 decode error'
}

function getErrorMsg (code, type) {
  // M63S++ resolves codes against the granular table first, then falls back
  // to the shared map for any code it does not list explicitly.
  if (type && type.includes('m63spp')) {
    return M63SPP_ERROR_MAP[code] || ERROR_MAP[code] || 'Unknown error'
  }
  const msg = ERROR_MAP[code] || 'Unknown error'
  return msg
}

function getAPICodeMsg (res) {
  if (res.Code === 23 && res.Msg === 'enc json load err') {
    return 'Invalid authentication'
  } else {
    const msg = API_MAP[res.Code] || 'Unknown code'
    return `Error ${res.Code}: ${msg}`
  }
}

module.exports = {
  getErrorMsg,
  getAPICodeMsg,
  ERROR_MAP,
  M63SPP_ERROR_MAP
}
